
# Init resources file
xrdb ~/.Xresources

## Configuration to start bspwm
## Start the sxhkd x hotkey daemon
sxhkd &
## Start a terminal for when bspwm starts
urxvt & 
## Start bspwm itself
exec bspwm

# Configuration to start i3 wm
#exec i3

# Config for XFCE
#exec startxfce4

