#
# ~/.bash_profile
#

export BASHPROFILE=1

# Aliases
#alias nvim='nvim -u ~/.vimrc'
#alias vi='nvim'
#alias vim='nvim'
alias vi='vim'

# Env variables
#export EDITOR='nvim'
export EDITOR='vim'

# Tab completion shows suggestions on single tab
set show-all-if-ambiguous on

[[ -f ~/.bashrc ]] && . ~/.bashrc

