#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export BASHRC=1

# Aliases
alias ls='ls --color=auto'

#alias nvim='nvim -u ~/.vimrc'
#alias vi='nvim'
#alias vim='nvim'
alias vi='vim'

# Env variables
#export EDITOR='nvim'
export EDITOR='vim'

# Tab completion shows suggestions on single tab
set show-all-if-ambiguous on

# Start the SSH agent systemd user
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

PS1='[\u@\h \W]\$ '

